# Dependencies
markdown:         redcarpet
pygments:         true

# Exclude
exclude: ['Rakefile', 'README.md', 'LICENSE.md']

# Permalinks
permalink:        /:year/:month/:day/:title/


# Asset Bundler
asset_bundler:
    dev: false

# Setup
title:            Luke Codes
tagline:          'A Code Blog'
description:      'The code blog of <a href="https://twitter.com/lukekarrys" target="_blank">@lukekarrys</a>.'
url:              http://lukecod.es

author:
  name:           'Luke Karrys'
  email:            'luke@lukekarrys.com'

paginate:         5

# Custom vars
links:
  home:             http://lukekarrys.com
  twitter:          https://twitter.com/lukekarrys
  github:           https://github.com/lukekarrys
