# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Exclude
exclude: ['README.md', 'LICENSE.md', 'package.json', 'package-lock.json', 'node_modules', 'Gemfile', 'Gemfile.lock']

# Permalinks
permalink:        /:year/:month/:day/:title/

# Asset Bundler
asset_bundler:
    dev: false

# Setup
title:            Luke Codes
tagline:          'A Code Blog'
description:      'The code blog of <a href="https://github.com/lukekarrys" target="_blank">Luke Karrys</a>.'
url:              http://lukecod.es
baseurl:          /

author:
  name:           'Luke Karrys'
  email:            'luke@lukekarrys.com'

paginate:         5

# Custom vars
links:
  home:             http://lukekarrys.com
  github:           https://github.com/lukekarrys
